apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gin-web
 
  labels:
    app:  gin-web
spec:
  selector:
    matchLabels:
      app: gin-web
      tier: service
  replicas: 2
  template:
    metadata:
      labels:
        app:  gin-web
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  gin-web
        image:  hosseinalizadeh/gin-web:1.0.1
        resources:
          requests:
            cpu: 125m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 180Mi
        readinessProbe:
          httpGet:
            path: /ping
            port: 90
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name:  PORT
          value:  "9090"  
        ports:
        - containerPort:  9090
          name:  gin-web
