apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  gin-web
  labels:
    app:  gin-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app:  gin-web
        tier: service
    spec:
      containers:
      - image: "hosseinalizadeh/gin-web:1.0.1"
        name:  gin-web
        resources:
          requests:
            cpu: "125m" 
            memory: "64Mi"
          limits:
              cpu: "250m" 
              memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9090
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  PORT
          value:  "9090"       
        ports:
        - containerPort:  9090
      restartPolicy: Always
      imagePullPolicy: Always